theme: jekyll-theme-dinky
title: About Me
description: You can find link to all of my releases and works-in-progress below.
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
